export default {
    background: require('../../assets/background.png'),
    background2: require('../../assets/bg.jpg'),
    undercons: require('./under_construction.jpg'),
    light: require('../../assets/light.png'),
    pump: require('../../assets/pumps.png'),
    monitor: require('../../assets/monitors.png'),
    dairy: require('../../assets/daily.png'),
    connection: require('../../assets/connection.png'),
    auto: require('../../assets/auto.png'),
    manuel: require('../../assets/manuel.png'),
    settings: require('../../assets/setting.png'),
    template: require('../../assets/template.png'),
    delete: require('../../assets/delete.png'),
    deviceIcon: require('../../assets/icon.png'),
    mythLight: require('../../assets/icon.png'),
    insta: require('../../assets/instagram.png'),
    checked: require('../../assets/blue-check.png'),
    sliderIcon: require('../../assets/iconLight.png'),
    chatbot: require('../../assets/aibot_one.png'),
    transparentIcon: require('../../assets/iconTrans.png'),
    simulation:require('../../assets/simulation.png'),
    tr:require('../../assets/tr.png'),
    en:require('../../assets/en.png'),
    newLogo:require('../../assets/newLogo.jpg'),


}
