export default {
    background: require('../../assets/background.png'),
    background2: require('../../assets/bg.jpg'),
    undercons: require('./under_construction.jpg'),
    delete: require('../../assets/delete.png'),
    deviceIcon: require('../../assets/icon.png'),
    mythLight: require('../../assets/icon.png'),
    insta: require('../../assets/instagram.png'),
    checked: require('../../assets/blue-check.png'),
    transparentIcon: require('../../assets/iconTrans.png'),
    simulation:require('../../assets/simulation.png'),
    tr:require('../../assets/tr.png'),
    en:require('../../assets/en.png'),
    newLogo:require('../../assets/newLogo.jpg'),
}
